language: minimal

dist: bionic
sudo: required

install:
  - if [ ! -d $HOME/.swiftenv/bin ]; then git clone https://github.com/kylef/swiftenv.git $HOME/.swiftenv; fi
  - export PATH="$HOME/.swiftenv/bin:$PATH"
  - eval "$(swiftenv init -)"
  - swiftenv install || true

jobs:
  include:
    - stage: build
      script: swift build
    - stage: test
      script: swift test

cache:
  directories:
    - $HOME/.swiftenv
    - .build
