language: shell

dist: bionic

env:
  - CODECOV_TOKEN="751a65e7-7962-454d-9080-697e0d8e4954"

install:
  - if [ ! -d $HOME/.swiftenv/bin ]; then git clone https://github.com/kylef/swiftenv.git $HOME/.swiftenv; fi
  - export PATH="$HOME/.swiftenv/bin:$PATH"
  - eval "$(swiftenv init -)"
  - swiftenv install || true

jobs:
  include:
    - stage: build
      script: swift build
    - stage: test
      script:
        - swift test --enable-code-coverage
      after_success:
        - llvm-cov export -format="text" .build/x86_64-unknown-linux/debug/DevMumblesPackageTests.xctest -instr-profile=.build/x86_64-unknown-linux/debug/codecov/default.profdata > info.lcov
        - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.swiftenv
    - .build
