version: "3.7"
services:
  web:
    build: .
    image: dev-mumbles
    working_dir: /mumbles
    tty: true
    stdin_open: true
    command: >
      /bin/sh -c "
        while ! nc -zv ${DB_HOST:-mumbles.db} ${DB_PORT:-5984};
        do
          echo 'CouchDB not ready' && sleep 5
        done
        if [ 404 = `curl -u admin:${DB_PASSWORD:-123456} --write-out %{http_code} --silent --output /dev/null http://${DB_HOST:-mumbles.db}:${DB_PORT:-5984}/_global_changes` ]; then
          curl -u ${DB_USER:-admin}:${DB_PASSWORD:-123456} -X PUT http://${DB_HOST:-mumbles.db}:${DB_PORT:-5984}/_global_changes
          curl -u ${DB_USER:-admin}:${DB_PASSWORD:-123456} -X PUT http://${DB_HOST:-mumbles.db}:${DB_PORT:-5984}/_replicator
          curl -u ${DB_USER:-admin}:${DB_PASSWORD:-123456} -X PUT http://${DB_HOST:-mumbles.db}:${DB_PORT:-5984}/_users
        fi
        swift run
      "
    volumes:
      - .:/mumbles:delegated
    ports:
      - "${HOST_PORT:-8080}:8080"
    networks:
      mumblesnet:
        aliases:
          - mumbles.localhost
    environment:
      DB_HOST: ${DB_HOST:-mumbles.db}
      DB_PORT: ${DB_PORT:-5984}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-123456}
    depends_on:
      - couchdb
  couchdb:
    image: couchdb:2.3.1
    volumes:
      - couchdata:/opt/couchdb/data:delegated
    ports:
      - "${DB_PORT:-5984}:5984"
    networks:
      mumblesnet:
        aliases:
          - mumbles.db
    environment:
      COUCHDB_USER: ${DB_USER:-admin}
      COUCHDB_PASSWORD: ${DB_PASSWORD:-123456}
networks:
  mumblesnet:
    external:
      name: mumbles_net
volumes:
  couchdata:
    driver: "local"
